version: "3.7"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    ports:
      - target: 5432
        published: $PGPORT
    volumes:
      - ./:/app
    working_dir: /app
